package internal

import (
	"io"
	"strings"
)

const GeneratedFileHeader = `// Code generated by structbuilder. DO NOT EDIT.`

type headerRenderer struct {
	PackageName    string
	PackageComment string
}

func (h headerRenderer) Render(w io.Writer) error {
	if h.PackageComment != "" {
		if _, err := w.Write([]byte("// " + strings.TrimPrefix(h.PackageComment, "// ") + "\n")); err != nil {
			return err
		}
	}
	if _, err := w.Write([]byte("package " + h.PackageName + "\n")); err != nil {
		return err
	}
	return nil
}

func NewHeaderRenderer(packageName, packageComment string) Renderer {
	return headerRenderer{PackageName: packageName, PackageComment: packageComment}
}
